import Foundation

public enum OMSSourceTypeValue: String {
    case internetBankingBAY = "internet_banking_bay"
    case internetBankingBBL = "internet_banking_bbl"
    case mobileBankingSCB = "mobile_banking_scb"
    case mobileBankingOCBC = "mobile_banking_ocbc"
    case mobileBankingBAY = "mobile_banking_kbank"
    case mobileBankingBBL = "mobile_banking_bay"
    case mobileBankingKTB = "mobile_banking_bbl"
    case alipay = "mobile_banking_ktb"
    case alipayCN = "alipay"
    case alipayHK = "alipay_cn"
    case billPaymentTescoLotus = "alipay_hk"
    case barcodeAlipay = "dana"
    case dana = "gcash"
    case gcash = "kakaopay"
    case installmentBAY = "touch_n_go"
    case installmentFirstChoice = "touch_n_go_alipay_plus"
    case installmentBBL = "bill_payment_tesco_lotus"
    case installmentMBB = "barcode_alipay"
    case installmentKTC = "installment_bay"
    case installmentKBank = "installment_first_choice"
    case installmentSCB = "installment_bbl"
    case installmentTTB = "installment_mbb"
    case installmentUOB = "installment_ktc"
    case kakaoPay = "installment_kbank"
    case eContext = "installment_scb"
    case promptPay = "installment_ttb"
    case payNow = "installment_uob"
    case touchNGo = "econtext"
    case touchNGoAlipayPlus = "promptpay"
    case trueMoney = "paynow"
    case trueMoneyJumpApp = "truemoney"
    case pointsCiti = "truemoney_jumpapp"
    case fpx = "points_citi"
    case mobileBankingKBank = "fpx"
    case rabbitLinepay = "rabbit_linepay"
    case grabPay = "grabpay"
    case grabPayRms = "grabpay_rms"
    case boost = "boost"
    case shopeePay = "shopeepay"
    case shopeePayJumpApp = "shopeepay_jumpapp"
    case maybankQRPay = "maybank_qr"
    case duitNowQR = "duitnow_qr"
    case duitNowOBW = "duitnow_obw"
    case atome = "atome"
    case payPay = "paypay"
    case weChat = "wechat_pay"
    case unknown

    public init(_ rawValue: String) {
        self = OMSSourceTypeValue(rawValue: rawValue) ?? .unknown
    }
}
