//
//  CountryInfo.swift
//  OmiseSDK
//
//  Created by Andrei Solovev on 8/6/23.
//  Copyright © 2023 Omise. All rights reserved.
//

import Foundation

struct CountryInfo: Codable, Equatable {
    let name: String
    let code: String
}

extension CountryInfo {

    static var `default`: CountryInfo?

    static func setDefaultCountryCode(_ code: String) {
        self.default = CountryInfo.all.first { $0.code == code }
    }

    static var avsCodes: [String] = ["US", "CA", "GB"]
    var isAVS: Bool {
        Self.avsCodes.contains(code)
    }
    
    static var all: [CountryInfo] = [
        .init(name: "Afghanistan", code: "AF"),
        .init(name: "Åland Islands", code: "AX"),
        .init(name: "Albania", code: "AL"),
        .init(name: "Algeria", code: "DZ"),
        .init(name: "American Samoa", code: "AS"),
        .init(name: "Andorra", code: "AD"),
        .init(name: "Angola", code: "AO"),
        .init(name: "Anguilla", code: "AI"),
        .init(name: "Antarctica", code: "AQ"),
        .init(name: "Angola", code: "AO"),
        .init(name: "Antigua and Barbuda", code: "AG"),
        .init(name: "Argentina", code: "AR"),
        .init(name: "Armenia", code: "AM"),
        .init(name: "Aruba", code: "AW"),
        .init(name: "Australia", code: "AU"),
        .init(name: "Austria", code: "AT"),
        .init(name: "Azerbaijan", code: "AZ"),
        .init(name: "Bahamas", code: "BS"),
        .init(name: "Bahrain", code: "BH"),
        .init(name: "Bangladesh", code: "BD"),
        .init(name: "Barbados", code: "BB"),
        .init(name: "Belarus", code: "BY"),
        .init(name: "Belgium", code: "BE"),
        .init(name: "Belize", code: "BZ"),
        .init(name: "Benin", code: "BJ"),
        .init(name: "Bermuda", code: "BM"),
        .init(name: "Bhutan", code: "BT"),
        .init(name: "Bolivia (Plurinational State of)", code: "BO"),
        .init(name: "Bonaire Sint Eustatius Saba", code: "BQ"),
        .init(name: "Bosnia and Herzegovina", code: "BA"),
        .init(name: "Botswana", code: "BW"),
        .init(name: "Bouvet Island", code: "BV"),
        .init(name: "Brazil", code: "BR"),
        .init(name: "British Indian Ocean Territory", code: "IO"),
        .init(name: "Brunei Darussalam", code: "BN"),
        .init(name: "Bulgaria", code: "BG"),
        .init(name: "Burkina Faso", code: "BF"),
        .init(name: "Burundi", code: "BI"),
        .init(name: "Cabo Verde", code: "CV"),
        .init(name: "Cambodia", code: "KH"),
        .init(name: "Cameroon", code: "CM"),
        .init(name: "Canada", code: "CA"),
        .init(name: "Cayman Islands", code: "KY"),
        .init(name: "Central African Republic", code: "CF"),
        .init(name: "Chad", code: "TD"),
        .init(name: "Chile", code: "CL"),
        .init(name: "China", code: "CN"),
        .init(name: "Christmas Island", code: "CX"),
        .init(name: "Cocos (Keeling) Islands", code: "CC"),
        .init(name: "Colombia", code: "CO"),
        .init(name: "Comoros", code: "KM"),
        .init(name: "Congo", code: "CG"),
        .init(name: "Congo, Democratic Republic of the", code: "CD"),
        .init(name: "Cook Islands", code: "CK"),
        .init(name: "Costa Rica", code: "CR"),
        .init(name: "Côte d\"Ivoire", code: "CI"),
        .init(name: "Croatia", code: "HR"),
        .init(name: "Cuba", code: "CU"),
        .init(name: "Curaçao", code: "CW"),
        .init(name: "Cyprus", code: "CY"),
        .init(name: "Czechia", code: "CZ"),
        .init(name: "Denmark", code: "DK"),
        .init(name: "Djibouti", code: "DJ"),
        .init(name: "Dominica", code: "DM"),
        .init(name: "Dominican Republic", code: "DO"),
        .init(name: "Ecuador", code: "EC"),
        .init(name: "Egypt", code: "EG"),
        .init(name: "El Salvador", code: "SV"),
        .init(name: "Equatorial Guinea", code: "GQ"),
        .init(name: "Eritrea", code: "ER"),
        .init(name: "Estonia", code: "EE"),
        .init(name: "Eswatini", code: "SZ"),
        .init(name: "Ethiopia", code: "ET"),
        .init(name: "Falkland Islands", code: "FK"),
        .init(name: "Faroe Islands", code: "FO"),
        .init(name: "Fiji", code: "FJ"),
        .init(name: "Finland", code: "FI"),
        .init(name: "France", code: "FR"),
        .init(name: "French Guiana", code: "GF"),
        .init(name: "French Polynesia", code: "PF"),
        .init(name: "French Southern Territories", code: "TF"),
        .init(name: "Gabon", code: "GA"),
        .init(name: "Gambia", code: "GM"),
        .init(name: "Georgia", code: "GE"),
        .init(name: "Germany", code: "DE"),
        .init(name: "Ghana", code: "GH"),
        .init(name: "Gibraltar", code: "GI"),
        .init(name: "Greece", code: "GR"),
        .init(name: "Greenland", code: "GL"),
        .init(name: "Grenada", code: "GD"),
        .init(name: "Guadeloupe", code: "GP"),
        .init(name: "Guam", code: "GU"),
        .init(name: "Guatemala", code: "GT"),
        .init(name: "Guernsey", code: "GG"),
        .init(name: "Guinea", code: "GN"),
        .init(name: "Guinea-Bissau", code: "GW"),
        .init(name: "Guyana", code: "GY"),
        .init(name: "Haiti", code: "HT"),
        .init(name: "Heard Island and McDonald Islands", code: "HM"),
        .init(name: "Holy See", code: "VA"),
        .init(name: "Honduras", code: "HN"),
        .init(name: "Hong Kong", code: "HK"),
        .init(name: "Hungary", code: "HU"),
        .init(name: "Iceland", code: "IS"),
        .init(name: "India", code: "IN"),
        .init(name: "Indonesia", code: "ID"),
        .init(name: "Iraq", code: "IQ"),
        .init(name: "Ireland", code: "IE"),
        .init(name: "Isle of Man", code: "IM"),
        .init(name: "Israel", code: "IL"),
        .init(name: "Italy", code: "IT"),
        .init(name: "Jamaica", code: "JM"),
        .init(name: "Japan", code: "JP"),
        .init(name: "Jersey", code: "JE"),
        .init(name: "Jordan", code: "JO"),
        .init(name: "Kazakhstan", code: "KZ"),
        .init(name: "Kenya", code: "KE"),
        .init(name: "Kiribati", code: "KI"),
        .init(name: "Korea, Republic of", code: "KR"),
        .init(name: "Kuwait", code: "KW"),
        .init(name: "Kyrgyzstan", code: "KG"),
        .init(name: "Lao People\"s Democratic Republic", code: "LA"),
        .init(name: "Latvia", code: "LV"),
        .init(name: "Lebanon", code: "LB"),
        .init(name: "Lesotho", code: "LS"),
        .init(name: "Liberia", code: "LR"),
        .init(name: "Libya", code: "LY"),
        .init(name: "Liechtenstein", code: "LI"),
        .init(name: "Lithuania", code: "LT"),
        .init(name: "Luxembourg", code: "LU"),
        .init(name: "Macao", code: "MO"),
        .init(name: "Madagascar", code: "MG"),
        .init(name: "Malawi", code: "MW"),
        .init(name: "Malaysia", code: "MY"),
        .init(name: "Maldives", code: "MV"),
        .init(name: "Mali", code: "ML"),
        .init(name: "Malta", code: "MT"),
        .init(name: "Marshall Islands", code: "MH"),
        .init(name: "Martinique", code: "MQ"),
        .init(name: "Mauritania", code: "MR"),
        .init(name: "Mauritius", code: "MU"),
        .init(name: "Mayotte", code: "YT"),
        .init(name: "Mexico", code: "MX"),
        .init(name: "Micronesia (Federated States of)", code: "FM"),
        .init(name: "Moldova, Republic of", code: "MD"),
        .init(name: "Monaco", code: "MC"),
        .init(name: "Mongolia", code: "MN"),
        .init(name: "Montenegro", code: "ME"),
        .init(name: "Montserrat", code: "MS"),
        .init(name: "Morocco", code: "MA"),
        .init(name: "Mozambique", code: "MZ"),
        .init(name: "Myanmar", code: "MM"),
        .init(name: "Namibia", code: "NA"),
        .init(name: "Nauru", code: "NR"),
        .init(name: "Nepal", code: "NP"),
        .init(name: "Netherlands", code: "NL"),
        .init(name: "New Caledonia", code: "NC"),
        .init(name: "New Zealand", code: "NZ"),
        .init(name: "Nicaragua", code: "NI"),
        .init(name: "Niger", code: "NE"),
        .init(name: "Nigeria", code: "NG"),
        .init(name: "Niue", code: "NU"),
        .init(name: "Norfolk Island", code: "NF"),
        .init(name: "Northern Mariana Islands", code: "MP"),
        .init(name: "North Macedonia", code: "MK"),
        .init(name: "Norway", code: "NO"),
        .init(name: "Oman", code: "OM"),
        .init(name: "Pakistan", code: "PK"),
        .init(name: "Palau", code: "PW"),
        .init(name: "Palestine, State of", code: "PS"),
        .init(name: "Panama", code: "PA"),
        .init(name: "Papua New Guinea", code: "PG"),
        .init(name: "Paraguay", code: "PY"),
        .init(name: "Peru", code: "PE"),
        .init(name: "Philippines", code: "PH"),
        .init(name: "Pitcairn", code: "PN"),
        .init(name: "Poland", code: "PL"),
        .init(name: "Portugal", code: "PT"),
        .init(name: "Puerto Rico", code: "PR"),
        .init(name: "Qatar", code: "QA"),
        .init(name: "Réunion", code: "RE"),
        .init(name: "Romania", code: "RO"),
        .init(name: "Russian Federation", code: "RU"),
        .init(name: "Rwanda", code: "RW"),
        .init(name: "Saint Barthélemy", code: "BL"),
        .init(name: "Saint Helena Ascension Island Tristan da Cunha", code: "SH"),
        .init(name: "Saint Kitts and Nevis", code: "KN"),
        .init(name: "Saint Lucia", code: "LC"),
        .init(name: "Saint Martin (French part)", code: "MF"),
        .init(name: "Saint Pierre and Miquelon", code: "PM"),
        .init(name: "Saint Vincent and the Grenadines", code: "VC"),
        .init(name: "Samoa", code: "WS"),
        .init(name: "San Marino", code: "SM"),
        .init(name: "Sao Tome and Principe", code: "ST"),
        .init(name: "Saudi Arabia", code: "SA"),
        .init(name: "Senegal", code: "SN"),
        .init(name: "Serbia", code: "RS"),
        .init(name: "Seychelles", code: "SC"),
        .init(name: "Sierra Leone", code: "SL"),
        .init(name: "Singapore", code: "SG"),
        .init(name: "Sint Maarten", code: "SX"),
        .init(name: "Slovakia", code: "SK"),
        .init(name: "Slovenia", code: "SI"),
        .init(name: "Solomon Islands", code: "SB"),
        .init(name: "Somalia", code: "SO"),
        .init(name: "South Africa", code: "ZA"),
        .init(name: "South Georgia and the South Sandwich Islands", code: "GS"),
        .init(name: "South Sudan", code: "SS"),
        .init(name: "Spain", code: "ES"),
        .init(name: "Sri Lanka", code: "LK"),
        .init(name: "Sudan", code: "SD"),
        .init(name: "Suriname", code: "SR"),
        .init(name: "Svalbard Jan Mayen", code: "SJ"),
        .init(name: "Sweden", code: "SE"),
        .init(name: "Switzerland", code: "CH"),
        .init(name: "Syrian Arab Republic", code: "SY"),
        .init(name: "Taiwan", code: "TW"),
        .init(name: "Tajikistan", code: "TJ"),
        .init(name: "Tanzania, United Republic of", code: "TZ"),
        .init(name: "Thailand", code: "TH"),
        .init(name: "Timor-Leste", code: "TL"),
        .init(name: "Togo", code: "TG"),
        .init(name: "Tokelau", code: "TK"),
        .init(name: "Tonga", code: "TO"),
        .init(name: "Trinidad and Tobago", code: "TT"),
        .init(name: "Tunisia", code: "TN"),
        .init(name: "Turkey", code: "TR"),
        .init(name: "Turkmenistan", code: "TM"),
        .init(name: "Turks and Caicos Islands", code: "TC"),
        .init(name: "Tuvalu", code: "TV"),
        .init(name: "Uganda", code: "UG"),
        .init(name: "Ukraine", code: "UA"),
        .init(name: "United Arab Emirates", code: "AE"),
        .init(name: "United Kingdom of Great Britain and Northern Ireland", code: "GB"),
        .init(name: "United States Minor Outlying Islands", code: "UM"),
        .init(name: "United States of America", code: "US"),
        .init(name: "Uruguay", code: "UY"),
        .init(name: "Uzbekistan", code: "UZ"),
        .init(name: "Vanuatu", code: "VU"),
        .init(name: "Venezuela (Bolivarian Republic of)", code: "VE"),
        .init(name: "Vietnam", code: "VN"),
        .init(name: "Virgin Islands (British)", code: "VG"),
        .init(name: "Virgin Islands", code: "VI"),
        .init(name: "Wallis and Futuna", code: "WF"),
        .init(name: "Western Sahara", code: "EH"),
        .init(name: "Yemen", code: "YE"),
        .init(name: "Zambia", code: "ZM"),
        .init(name: "Zimbabwe", code: "ZW")
    ]
}
