@import Foundation;


typedef NSString * OMSSourceTypeValue NS_EXTENSIBLE_STRING_ENUM;

extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingBAY;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingBBL;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueMobileBankingSCB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueMobileBankingOCBCPAO;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueMobileBankingOCBC;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueMobileBankingBAY;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueMobileBankingBBL;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueMobileBankingKTB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueAlipay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueAlipayCN;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueAlipayHK;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueBillPaymentTescoLotus;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueBarcodeAlipay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueDana;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueGcash;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentBAY;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentFirstChoice;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentBBL;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentMBB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentKTC;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentKBank;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentSCB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentCiti;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentTTB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentUOB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueKakaoPay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueEContext;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValuePromptPay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValuePayNow;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueTouchNGo;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueTouchNGoAlipayPlus;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueTrueMoney;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueTrueMoneyJumpApp;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValuePointsCiti;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueFpx;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueMobileBankingKBank;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueRabbitLinepay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueGrabPay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueGrabPayRms;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueBoost;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueShopeePay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueShopeePayJumpApp;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueMaybankQRPay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueDuitNowQR;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueDuitNowOBW;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueAtome;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValuePayPay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueWeChat;


typedef NSString * OMSSupportedCurrencyCode NS_EXTENSIBLE_STRING_ENUM;

extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeTHB;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeJPY;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeIDR;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeSGD;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeUSD;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeGBP;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeEUR;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeMYR;

extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeAUD;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeCAD;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeCHF;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeCNY;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeDKK;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeHKD;
