@import Foundation;


typedef NSString * OMSSourceTypeValue NS_EXTENSIBLE_STRING_ENUM;

extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingBAY;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingKTB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingSCB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingBBL;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueAlipay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueBillPaymentTescoLotus;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueBarcodeAlipay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentBAY;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentFirstChoice;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentBBL;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentKTC;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentKBank;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentSCB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueEContext;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValuePromptPay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValuePayNow;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueTrueMoney;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValuePointsCiti;
