@import Foundation;


typedef NSString * OMSSourceTypeValue NS_EXTENSIBLE_STRING_ENUM;

extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingBAY;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingKTB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingSCB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingBBL;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueAlipay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueBillPaymentTescoLotus;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueBarcodeAlipay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentBAY;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentFirstChoice;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentBBL;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentKTC;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInstallmentKBank;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueEContext;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValuePromptPay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValuePayNow;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueTrueMoney;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValuePointsCiti;


typedef NSString * OMSSupportedCurrencyCode NS_EXTENSIBLE_STRING_ENUM;

extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeTHB;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeJPY;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeIDR;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeSGD;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeUSD;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeGBP;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeEUR;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeMYR;

extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeAUD;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeCAD;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeCHF;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeCNY;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeDKK;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeHKD;

