@import Foundation;


typedef NSString * OMSSourceTypeValue NS_EXTENSIBLE_STRING_ENUM;

extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingBAY;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingKTB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingSCB;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueInternetBankingBBL;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueAlipay;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueBillPaymentTescoLotus;
extern OMSSourceTypeValue const _Nonnull OMSSourceTypeValueBarcodeAlipay;


typedef NSString * OMSSupportedCurrencyCode NS_EXTENSIBLE_STRING_ENUM;

extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeTHB;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeJPY;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeIDR;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeSGD;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeUSD;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeGBP;
extern OMSSupportedCurrencyCode const _Nonnull OMSSupportedCurrencyCodeEUR;

